$WebServices = @(
@{URI="http://vagrant-2012-r2/altiris/ASDK.DeploymentSolution/DSTaskManagementService.asmx";ServiceName="DSTaskManagement"},
@{URI="http://vagrant-2012-r2/altiris/ASDK.NS.SoftwareDelivery/SWDSolnAdvertisementManagementService.asmx";ServiceName="SWDSolnAdvertisementManagement"},
@{URI="http://vagrant-2012-r2/altiris/ASDK.NS.SoftwareDelivery/SWDSolnPackageManagementService.asmx";ServiceName="SWDSolnPackageManagement"},
@{URI="http://vagrant-2012-r2/altiris/ASDK.NS.SoftwareDelivery/SWDSolnProgramManagementService.asmx";ServiceName="SWDSolnProgramManagement"},
@{URI="http://vagrant-2012-r2/altiris/ASDK.NS/ItemManagementService.asmx";ServiceName="ItemManagement"},
@{URI="http://vagrant-2012-r2/altiris/ASDK.NS/CollectionManagementService.asmx";ServiceName="CollectionManagement"},
@{URI="http://vagrant-2012-r2/altiris/ASDK.NS/HierarchyManagementService.asmx";ServiceName="HierarchyManagement"},
@{URI="http://vagrant-2012-r2/altiris/ASDK.NS/ReportManagementService.asmx";ServiceName="ReportManagement"},
@{URI="http://vagrant-2012-r2/altiris/ASDK.NS/ResourceManagementService.asmx";ServiceName="ResourceManagement"},
@{URI="http://vagrant-2012-r2/altiris/ASDK.NS/ScopingManagementService.asmx";ServiceName="ScopingManagement"},
@{URI="http://vagrant-2012-r2/altiris/ASDK.NS/SecurityManagementService.asmx";ServiceName="SecurityManagement"},
@{URI="http://vagrant-2012-r2/altiris/ASDK.SMF/InventoryRuleManagementService.asmx";ServiceName="InventoryRuleManagement"},
@{URI="http://vagrant-2012-r2/altiris/ASDK.SMF/SoftwareCommandLineManagementService.asmx";ServiceName="SoftwareCommandLineManagement"},
@{URI="http://vagrant-2012-r2/altiris/ASDK.SMF/SoftwareComponentManagementService.asmx";ServiceName="SoftwareComponentManagement"},
@{URI="http://vagrant-2012-r2/altiris/ASDK.SMF/SoftwarePackageManagementService.asmx";ServiceName="SoftwarePackageManagement"},
@{URI="http://vagrant-2012-r2/altiris/ASDK.SMF/SoftwareProductManagementService.asmx";ServiceName="SoftwareProductManagement"},
@{URI="http://vagrant-2012-r2/altiris/ASDK.SWM/SoftwareDeliveryPolicyManagementService.asmx";ServiceName="SoftwareDeliveryPolicyManagement"},
@{URI="http://vagrant-2012-r2/altiris/ASDK.SWM/SoftwarePortalManagementService.asmx";ServiceName="SoftwarePortalManagement"},
@{URI="http://vagrant-2012-r2/altiris/ASDK.SWM/SoftwareTasksManagementService.asmx";ServiceName="SoftwareTasksManagement"},
@{URI="http://vagrant-2012-r2/altiris/ASDK.Task/TaskManagementService.asmx";ServiceName="TaskManagement"})

$Credential = Get-Credential

foreach ($WebserviceUri in $WebServices)
{
    $Webservice = New-WebServiceProxy -Uri $WebserviceUri.Uri -Credential $Credential
    ConvertTo-Function -WebService $Webservice -ServiceName $WebServiceUri.ServiceName | Out-File C:\Users\wmrm\Desktop\GitHub\PowerShellSymantecAltirisASDK\AutoGeneratedPS.ps1 -Append
}